import 'dart:async';

import 'package:flutter/material.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const _localizedValues = <String, Map<String, String>>{
    'en': {
      'app_name': 'Driver Pro',
      'next': 'Next',
      'skip': 'Skip',
      'get_started': 'Get Started',
      'login': 'Login',
      'register': 'Register',
      'continue_guest': 'Continue as Guest',
      'email_or_phone': 'Email or phone',
      'password': 'Password',
      'home': 'Home',
      'enable_location': 'Enable Location',
      'enable_location_description':
          'Turn on your location services to start accepting rides.',
      'continue': 'Continue',
      'incoming_ride': 'Incoming Ride',
      'accept': 'Accept',
      'decline': 'Decline',
      'online': 'Online',
      'offline': 'Offline',
      'earnings': 'Earnings',
      'history': 'History',
      'my_rides': 'My Rides',
      'performance': 'Performance',
      'settings': 'Settings',
      'language': 'Language',
      'dark_mode': 'Dark Mode',
      'primary_color': 'Primary color',
      'notifications': 'Notifications',
      'ai_placeholder': 'AI insights coming soon.',
      'search': 'Search',
      'guest': 'Guest',
      'logout': 'Logout',
      'profile': 'Profile',
      'documents': 'Documents',
      'help': 'Help & FAQ',
      'catalog': 'Catalog',
      'compare': 'Compare',
      'onboarding_title_1': 'Drive smarter',
      'onboarding_desc_1': 'Discover smarter ways to navigate your city.',
      'onboarding_title_2': 'Earn confidently',
      'onboarding_desc_2': 'Track earnings and stay on top of your goals.',
      'onboarding_title_3': 'Stay connected',
      'onboarding_desc_3': 'Chat with passengers and support instantly.',
      'my_earnings_title': 'My Earnings',
      'add_new_card': 'Add new card',
      'available_balance': 'Available balance',
      'no_rides_found': 'No rides found',
      'search_history': 'Search history',
      'search_catalog': 'Search catalog',
      'catalog_items': 'Catalog Items',
      'compare_items': 'Compare Items',
      'documents_title': 'Documents',
      'upload': 'Upload',
      'contact_support': 'Contact Support',
      'chats': 'Chats',
      'on_trip_title': 'On Trip',
      'rate_trip': 'Rate Trip',
      'how_was_trip': 'How was your trip?',
      'submit': 'Submit',
      'cancel': 'Cancel',
      'no_completed_trip': 'No completed trip.',
      'no_active_trip': 'No active trip.',
      'no_catalog_found': 'No catalog items found',
      'save': 'Save',
      'profile_title': 'Profile',
      'settings_title': 'Settings',
      'search_data': 'Search data',
      'rides_section': 'Rides',
      'calling': 'Calling...',
      'message_sent': 'Message sent',
      'status': 'Status',
      'metric': 'Metric',
      'total_trips': 'Total trips',
      'completion_rate': 'Completion rate',
      'average_rating': 'Average rating',
      'total_distance': 'Total distance',
      'no_rides_available': 'No rides available',
      'pickup': 'Pickup',
      'destination': 'Destination',
      'invalid_credentials': 'Invalid credentials',
      'forgot_password': 'Forgot password?',
      'send_reset_link': 'Send reset link',
      'required': 'Required',
      'enter_valid_email_phone': 'Enter valid email or phone',
      'password_too_short': 'Password too short',
      'name': 'Name',
      'email': 'Email',
      'phone': 'Phone',
      'confirm_password': 'Confirm Password',
      'update_avatar': 'Update avatar URL',
      'close': 'Close',
      'profile_updated': 'Profile updated locally.',
      'car_model': 'Car model',
      'car_plate': 'Car plate',
      'passwords_do_not_match': 'Passwords do not match',
      'trip_details': 'Trip Details',
      'call': 'Call',
      'message': 'Message',
      'select_items_to_compare': 'Select items to compare.',
      'price': 'Price',
      'distance': 'Distance',
      'time': 'Time',
      'smart_insights': 'Smart insights',
      'ride_insights': 'Ride insights',
      'catalog_insights': 'Catalog insights',
      'projected_payout_label': 'Projected payout',
      'surge_multiplier_label': 'Surge multiplier',
      'cancellation_risk_label': 'Cancellation risk',
      'demand_trend_label': 'Demand trend',
      'distance_hint_label': 'Distance insight',
      'bundle_value_label': 'Bundle value',
      'rating_strength_label': 'Rating strength',
      'shift_planner': 'Shift planner',
      'suggested_follow_up': 'Suggested follow-up',
      'hotspot_window': 'Hotspot window',
      'selected_label': 'Selected',
      'ready_to_compare': 'Ready to compare',
      'select_two_notice': 'Pick at least two rides to compare.',
      'search_summary': 'Search summary',
      'rides_label': 'Rides',
      'catalog_label': 'Catalog',
      'recent_searches': 'Recent searches',
      'clear': 'Clear',
      'no_recent_searches': 'No recent searches yet',
      'demand_peak': 'Peak demand',
      'demand_balanced': 'Steady demand',
      'demand_calm': 'Calm demand',
      'planning_tip_label': 'Planning tip',
      'insights_center': 'Insights studio',
      'view_full_insights': 'View full insights',
      'strategy_lab': 'Strategy lab',
      'strategy_lab_subtitle': 'Design the next shift blueprint with predictive plays.',
      'open_strategy_lab': 'Open strategy lab',
      'wellness_studio': 'Wellness studio',
      'wellness_intro': 'Balance your shift with mindful resets and momentum.',
      'wellness_alignment': 'Alignment',
      'wellness_energy': 'Energy',
      'wellness_focus': 'Focus',
      'wellness_check_in_title': 'Shift check-in',
      'wellness_check_in_body': 'Tune energy and focus to personalise your boosts.',
      'reset_rhythm': 'Reset rhythm',
      'vibe_calm': 'Calm clarity',
      'vibe_focus': 'Deep focus',
      'vibe_energize': 'Active boost',
      'wellness_spotlight': 'Spotlight ritual',
      'wellness_completed': 'Completed today',
      'wellness_tap_to_mark': 'Tap to log progress',
      'breath_sequences': 'Breath sequences',
      'wellness_no_sequences': 'No breath sequences yet',
      'seconds_short': 's',
      'cycles_label': 'cycles',
      'mindful_rituals': 'Mindful rituals',
      'wellness_no_rituals': 'No rituals available yet',
      'micro_breaks': 'Micro breaks',
      'wellness_no_breaks': 'No micro breaks queued',
      'wellness_ai_tip_1': 'Pair your preferred vibe with planner windows for smarter resets.',
      'wellness_ai_tip_2': 'Completed rituals nudge alignment and goal confidence.',
      'wellness_ai_tip_3': 'Daily check-ins will power richer guidance in upcoming releases.',
      'wellness_mini_header': 'Mind-body snapshot',
      'momentum_hub': 'Momentum studio',
      'momentum_pulse_title': 'Momentum pulse',
      'momentum_level': 'Level',
      'momentum_xp': 'XP',
      'momentum_streak': 'Streak',
      'momentum_tracks_header': 'Focus tracks',
      'momentum_milestone_header': 'Track milestones',
      'momentum_milestone_completed': 'Milestone complete! Momentum boosted.',
      'momentum_step_logged': 'Progress logged into your track.',
      'momentum_done': 'Completed',
      'momentum_action_next': 'Next action',
      'momentum_challenges_header': 'Live challenges',
      'momentum_challenge_complete': 'Challenge complete! XP rewarded.',
      'momentum_challenge_progress': 'Challenge progress logged.',
      'momentum_mark_progress': 'Log progress',
      'momentum_no_challenges': 'No active challenges right now.',
      'momentum_signals_header': 'Coach signals',
      'momentum_refresh_toast': 'Momentum streams refreshed.',
      'momentum_track_switched': 'Focus track updated.',
      'momentum_ai_tip_1':
          'Dial into one focus track per shift to keep momentum sharp.',
      'momentum_ai_tip_2':
          'Logging micro-progress nudges XP gains and unlocks new levels.',
      'momentum_ai_tip_3':
          'Coach signals remix with each refresh—sync them with planner cues.',
      'momentum_quick_header': 'Momentum snapshot',
      'community_lounge': 'Community lounge',
      'community_refresh': 'Refresh pulse',
      'community_crews': 'Crew circles',
      'community_beacons': 'Live beacons',
      'community_no_beacons': 'No beacons yet — drop the first insight.',
      'community_sprints': 'Crew sprints',
      'community_no_sprints': 'No sprints scheduled yet.',
      'community_resources': 'Shared resources',
      'community_no_resources': 'No resources saved yet.',
      'community_pulse': 'Community pulse',
      'community_ai_tip':
          'Share a beacon after each shift to unlock collaborative boosts.',
      'community_collaboration': 'Collaboration score',
      'community_share_rate': 'Share rate',
      'community_assist_rate': 'Assist cadence',
      'community_active_drivers': 'Active drivers',
      'community_energy': 'Circle energy',
      'community_next_sync': 'Next sync',
      'community_boosts': 'boosts',
      'community_boost': 'Boost',
      'community_boosted': 'Boosted',
      'community_join_sprint': 'Join sprint',
      'community_sprint_joined': 'Joined',
      'community_save': 'Save',
      'community_saved': 'Saved',
      'community_quick_header': 'Community snapshot',
      'community_open_full': 'Open community lounge',
      'impact_studio': 'Impact studio',
      'impact_refresh': 'Refresh impact pulse',
      'impact_focus_modes': 'Focus modes',
      'impact_theme_efficiency': 'Efficiency',
      'impact_theme_sustainability': 'Sustainability',
      'impact_theme_experience': 'Rider delight',
      'impact_pulse_title': 'Impact pulse',
      'impact_city_label': 'Primary zone',
      'impact_co2_saved': 'CO₂ saved',
      'impact_clean_km': 'Clean km',
      'impact_renewable_share': 'Renewable share',
      'impact_streak': 'Impact streak',
      'impact_streak_days': 'days',
      'impact_highlights': 'Highlights',
      'impact_goals': 'Impact goals',
      'impact_goal_target': 'Target',
      'impact_goal_progress_hint': 'Slide to log today’s progress.',
      'impact_initiatives': 'Impact initiatives',
      'impact_join': 'Join',
      'impact_joined': 'Joined',
      'impact_actions': 'Micro-actions',
      'impact_mark_complete': 'Mark done',
      'impact_completed': 'Done',
      'impact_ripples': 'City ripples',
      'impact_quick_header': 'Impact snapshot',
      'impact_open_full': 'Open impact studio',
      'innovation_lab': 'Innovation lab',
      'innovation_pulse_card': 'Innovation pulse',
      'innovation_readiness': 'Readiness',
      'innovation_temperature': 'Lab temperature',
      'innovation_focus_lanes': 'Focus lanes',
      'innovation_energy_bursts': 'Energy bursts',
      'innovation_rotate_focus': 'Rotate focus lanes',
      'innovation_pipeline': 'Prototype pipeline',
      'innovation_no_prototypes': 'No prototypes staged yet.',
      'innovation_stage': 'Stage',
      'innovation_confidence': 'Confidence',
      'innovation_next_step': 'Next step',
      'innovation_last_note': 'Lab note',
      'innovation_advance': 'Advance prototype',
      'innovation_progress_updated': 'Prototype advanced inside the lab.',
      'innovation_experiment_grid': 'Active experiments',
      'innovation_no_experiments': 'No experiments running yet.',
      'innovation_blueprint_deck': 'Blueprint deck',
      'innovation_no_blueprints': 'No blueprints drafted yet.',
      'innovation_owner': 'Owner',
      'innovation_horizon': 'Horizon',
      'innovation_ai_headline': 'Lab intelligence preview',
      'innovation_ready_score_label': 'Readiness level',
      'innovation_focus_lane_label': 'Focus lanes',
      'innovation_next_review_on': 'Next review: {slot}',
      'mastery_studio': 'Mastery studio',
      'mastery_quick_header': 'Mastery pulse',
      'mastery_progress': 'Momentum',
      'mastery_energy_level': 'Energy',
      'mastery_micro_practice': 'Micro-practice',
      'mastery_module_progress_label': 'Module progress',
      'mastery_focus_pathways': 'Focus pathways',
      'mastery_mark_lesson': 'Mark drill complete',
      'mastery_lessons_done': 'Completed lessons',
      'mastery_next_action': 'Next action',
      'mastery_focus_active': 'Focus active',
      'mastery_focus_toggle': 'Set as focus',
      'mastery_workshops_title': 'Upcoming workshops',
      'mastery_enroll': 'Enroll',
      'mastery_leave': 'Leave',
      'mastery_badges_title': 'Badges in progress',
      'mastery_badge_unlocked': 'Unlocked',
      'mastery_badge_locked': 'Locked',
      'mastery_reflections_title': 'Reflections',
      'mastery_reflection_placeholder': 'What did you learn today?',
      'mastery_save_reflection': 'Save reflection',
      'mastery_empty_reflections': 'No reflections yet.',
      'mastery_refresh': 'Refresh pulse',
      'mastery_ai_hint': 'Tactical mastery insight',
      'mastery_coach_message': 'Coach note',
      'mastery_focus_label': 'Focus',
      'mastery_view_full': 'Open mastery studio',
      'horizon_studio': 'Horizon studio',
      'horizon_ai_headline': 'Future horizon insights',
      'horizon_ai_alignment': 'Alignment score',
      'horizon_ai_confidence': 'Confidence',
      'horizon_ai_focus': 'Focus themes',
      'horizon_ai_signals': 'Signal highlights',
      'horizon_ai_window': 'Next pulse window: {slot}',
      'horizon_ai_question': 'Guiding question: {question}',
      'horizon_pulse_card': 'Future pulse',
      'horizon_alignment': 'Alignment',
      'horizon_confidence': 'Confidence',
      'horizon_runway_days': 'Runway days',
      'horizon_next_window': 'Next window',
      'horizon_guiding_question': 'Guiding question',
      'horizon_focus_themes': 'Focus themes',
      'horizon_signal_highlights': 'Signal highlights',
      'horizon_raise_alignment': 'Elevate alignment',
      'horizon_cool_alignment': 'Cool alignment',
      'horizon_refresh_pulse': 'Refresh pulse',
      'horizon_scenarios': 'Scenarios on watch',
      'horizon_probability': 'Probability',
      'horizon_impact': 'Impact',
      'horizon_focus_cta': 'Set as focus',
      'horizon_focus_active': 'Focus locked',
      'horizon_runway': 'Runway checklist',
      'horizon_flag_signal': 'Pin signal',
      'horizon_unflag_signal': 'Unpin signal',
      'horizon_signals': 'Signals board',
      'horizon_momentum': 'Momentum',
      'horizon_blueprints': 'Blueprint deck',
      'horizon_advance_blueprint': 'Advance stage',
      'horizon_actions_label': 'Micro-actions',
      'horizon_quick_header': 'Horizon preview',
      'horizon_open_full': 'Open horizon studio',
      'fusion_studio': 'Fusion studio',
      'fusion_intro':
          'Blend focus threads and experiments to unlock richer rider journeys.',
      'fusion_ai_headline': 'Creative fusion preview',
      'fusion_alignment': 'Alignment',
      'fusion_cohesion': 'Cohesion',
      'fusion_window_label': 'Window',
      'fusion_focus_label': 'Focus thread',
      'fusion_next_sync': 'Next sync',
      'fusion_refresh': 'Refresh fusion pulse',
      'fusion_strands_title': 'Focus threads',
      'fusion_flow': 'Flow',
      'fusion_canvas_title': 'Canvas lanes',
      'fusion_canvas_empty': 'No canvas lanes available yet.',
      'fusion_canvas_heat': 'Heat',
      'fusion_canvas_cohesion': 'Cohesion',
      'fusion_experiments_title': 'Experiments',
      'fusion_experiments_empty': 'No experiments launched yet.',
      'fusion_confidence': 'Confidence',
      'fusion_stage': 'Stage',
      'fusion_activate': 'Activate',
      'fusion_pause': 'Pause',
      'fusion_signals_title': 'Signals',
      'fusion_signals_empty': 'No signals detected yet.',
      'fusion_capture': 'Capture',
      'fusion_release': 'Release',
      'fusion_quick_header': 'Fusion snapshot',
      'fusion_quick_focus': 'Focus',
      'fusion_quick_alignment': 'Alignment',
      'fusion_quick_cohesion': 'Cohesion',
      'fusion_quick_open': 'Open fusion studio',
      'cosmos_studio': 'Cosmos studio',
      'cosmos_pulse_title': 'Constellation pulse',
      'cosmos_magnetism': 'Magnetism',
      'cosmos_signal': 'Signal strength',
      'cosmos_alliances': 'Active alliances',
      'cosmos_window_label': 'Window',
      'cosmos_focus_label': 'Focus',
      'cosmos_next_trajectory': 'Next trajectory',
      'cosmos_constellations_title': 'Constellation field',
      'cosmos_resonance': 'Resonance',
      'cosmos_tap_to_focus': 'Tap to switch focus',
      'cosmos_orbits_title': 'Orbit lanes',
      'cosmos_beacons_title': 'Beacon boosts',
      'cosmos_urgency': 'Urgency',
      'cosmos_boost': 'Boost',
      'cosmos_release': 'Release',
      'cosmos_expeditions_title': 'Expeditions',
      'cosmos_enroll': 'Join expedition',
      'cosmos_leave': 'Leave expedition',
      'cosmos_artifacts_title': 'Artifacts vault',
      'cosmos_save': 'Save',
      'cosmos_saved': 'Saved',
      'cosmos_intro': 'Track alliance lanes and orbit boosts across your shift.',
      'cosmos_refresh': 'Refresh cosmos pulse',
      'cosmos_boosted_message': 'Beacon boost armed.',
      'cosmos_unboosted_message': 'Beacon boost relaxed.',
      'cosmos_enrolled_message': 'Expedition aligned for tonight.',
      'cosmos_removed_message': 'Expedition paused.',
      'cosmos_saved_message': 'Artifact saved to vault.',
      'cosmos_unsaved_message': 'Artifact removed from vault.',
      'cosmos_quick_header': 'Cosmos snapshot',
      'cosmos_quick_window': 'Active window',
      'cosmos_quick_focus': 'Focus arc',
      'cosmos_quick_open': 'Open cosmos studio',
      'impact_focus_updated': 'Impact focus refreshed.',
      'impact_goal_updated': 'Impact goal updated.',
      'impact_initiative_joined_toast': 'Initiative preference saved.',
      'impact_action_completed_toast': 'Impact action tracked.',
      'impact_ai_tip':
          'Future AI will expand these climate-positive recommendations automatically.',
      'open_wellness_full': 'Open wellness studio',
      'weekly_goal': 'Weekly earning goal',
      'goal_progress': 'Goal progress',
      'goal_recommendation': 'Recommended target:',
      'goal_reached': 'Great! You already reached your goal.',
      'target_reach_estimate': 'Projected to reach in',
      'adjust_goal': 'Adjust goal',
      'minutes_short': 'min',
      'rides_short': 'rides',
      'heatmap_hint': 'Intensity indicates demand opportunity by block.',
      'focus_areas': 'Focus areas',
      'demand_heatmap': 'Demand heatmap',
      'trend_pulses': 'Live pulses',
      'refresh_insights': 'Refresh insights',
      'trend_rising': 'Rising',
      'trend_cooling': 'Cooling',
      'trend_flat': 'Steady',
      'goal_updated': 'Goal updated',
      'weekday_mon': 'Mon',
      'weekday_tue': 'Tue',
      'weekday_wed': 'Wed',
      'weekday_thu': 'Thu',
      'weekday_fri': 'Fri',
      'weekday_sat': 'Sat',
      'weekday_sun': 'Sun',
      'slot_morning': 'Morning',
      'slot_midday': 'Midday',
      'slot_evening': 'Evening',
      'planner_projected_earnings': 'Projected earnings',
      'planner_expected_trips': 'Expected trips',
      'planner_avg_demand': 'Average demand',
      'planner_confidence': 'Confidence',
      'planner_focus_label': 'Focus minutes',
      'planner_autonomous_mode': 'Autopilot boost',
      'planner_autonomous_hint': 'Enable proactive nudges and smart stacking.',
      'planner_metrics_label': 'Scenario metrics',
      'planner_timeline': 'Timeline blueprint',
      'planner_actions': 'Momentum actions',
      'planner_regenerate': 'Re-simulate plan',
      'planner_focus_area': 'Focus area',
      'planner_surge': 'Surge lift',
      'planner_risk': 'Risk',
      'planner_tags': 'Tags',
      'planner_impact': 'Impact',
    },
    'ar': {
      'app_name': 'سائق برو',
      'next': 'التالي',
      'skip': 'تخطي',
      'get_started': 'ابدأ الآن',
      'login': 'تسجيل الدخول',
      'register': 'إنشاء حساب',
      'continue_guest': 'المتابعة كضيف',
      'email_or_phone': 'البريد أو الهاتف',
      'password': 'كلمة المرور',
      'home': 'الرئيسية',
      'enable_location': 'تفعيل الموقع',
      'enable_location_description':
          'قم بتشغيل خدمات الموقع لبدء قبول الرحلات.',
      'continue': 'متابعة',
      'incoming_ride': 'رحلة واردة',
      'accept': 'قبول',
      'decline': 'رفض',
      'online': 'متصل',
      'offline': 'غير متصل',
      'earnings': 'الأرباح',
      'history': 'السجل',
      'my_rides': 'رحلاتي',
      'performance': 'الأداء',
      'settings': 'الإعدادات',
      'language': 'اللغة',
      'dark_mode': 'الوضع الداكن',
      'primary_color': 'اللون الرئيسي',
      'notifications': 'الإشعارات',
      'ai_placeholder': 'تحليلات الذكاء الاصطناعي قريباً.',
      'search': 'بحث',
      'guest': 'ضيف',
      'logout': 'تسجيل الخروج',
      'profile': 'الملف الشخصي',
      'documents': 'الوثائق',
      'help': 'المساعدة والأسئلة',
      'catalog': 'كتالوج',
      'compare': 'مقارنة',
      'onboarding_title_1': 'قد بأذكى طريقة',
      'onboarding_desc_1': 'اكتشف طرقاً أذكى للتنقل في مدينتك.',
      'onboarding_title_2': 'اربح بثقة',
      'onboarding_desc_2': 'تابع أرباحك وحقق أهدافك.',
      'onboarding_title_3': 'ابقَ على اتصال',
      'onboarding_desc_3': 'تواصل مع الركاب والدعم فوراً.',
      'my_earnings_title': 'أرباحي',
      'add_new_card': 'إضافة بطاقة جديدة',
      'available_balance': 'الرصيد المتاح',
      'no_rides_found': 'لا توجد رحلات',
      'search_history': 'بحث في السجل',
      'search_catalog': 'بحث في الكتالوج',
      'catalog_items': 'عناصر الكتالوج',
      'compare_items': 'مقارنة العناصر',
      'documents_title': 'الوثائق',
      'upload': 'رفع',
      'contact_support': 'اتصل بالدعم',
      'chats': 'المحادثات',
      'on_trip_title': 'رحلة جارية',
      'rate_trip': 'تقييم الرحلة',
      'how_was_trip': 'كيف كانت رحلتك؟',
      'submit': 'إرسال',
      'cancel': 'إلغاء',
      'no_completed_trip': 'لا توجد رحلة مكتملة.',
      'no_active_trip': 'لا توجد رحلة نشطة.',
      'no_catalog_found': 'لا توجد عناصر كتالوج',
      'save': 'حفظ',
      'profile_title': 'الملف الشخصي',
      'settings_title': 'الإعدادات',
      'search_data': 'بحث في البيانات',
      'rides_section': 'الرحلات',
      'calling': 'جارٍ الاتصال...',
      'message_sent': 'تم إرسال الرسالة',
      'status': 'الحالة',
      'metric': 'المؤشر',
      'total_trips': 'إجمالي الرحلات',
      'completion_rate': 'نسبة الإكمال',
      'average_rating': 'متوسط التقييم',
      'total_distance': 'إجمالي المسافة',
      'no_rides_available': 'لا توجد رحلات متاحة',
      'pickup': 'الانطلاق',
      'destination': 'الوجهة',
      'invalid_credentials': 'بيانات دخول غير صحيحة',
      'forgot_password': 'نسيت كلمة المرور؟',
      'send_reset_link': 'إرسال رابط إعادة التعيين',
      'required': 'مطلوب',
      'enter_valid_email_phone': 'أدخل بريداً إلكترونياً أو هاتفاً صالحاً',
      'password_too_short': 'كلمة المرور قصيرة',
      'name': 'الاسم',
      'email': 'البريد الإلكتروني',
      'phone': 'الهاتف',
      'confirm_password': 'تأكيد كلمة المرور',
      'update_avatar': 'تحديث رابط الصورة',
      'close': 'إغلاق',
      'profile_updated': 'تم تحديث الملف محلياً.',
      'car_model': 'طراز السيارة',
      'car_plate': 'رقم اللوحة',
      'passwords_do_not_match': 'كلمتا المرور غير متطابقتين',
      'trip_details': 'تفاصيل الرحلة',
      'call': 'اتصال',
      'message': 'رسالة',
      'select_items_to_compare': 'اختر عناصر للمقارنة.',
      'price': 'السعر',
      'distance': 'المسافة',
      'time': 'الوقت',
      'smart_insights': 'رؤى ذكية',
      'ride_insights': 'تحليلات الرحلة',
      'catalog_insights': 'تحليلات الكتالوج',
      'projected_payout_label': 'العائد المتوقع',
      'surge_multiplier_label': 'معامل التسعير',
      'cancellation_risk_label': 'مخاطر الإلغاء',
      'demand_trend_label': 'اتجاه الطلب',
      'distance_hint_label': 'معلومة المسافة',
      'bundle_value_label': 'قيمة الباقة',
      'rating_strength_label': 'قوة التقييم',
      'shift_planner': 'مخطط الوردية',
      'suggested_follow_up': 'اقتراح الرحلة التالية',
      'hotspot_window': 'نافذة النقاط الساخنة',
      'selected_label': 'المحدد',
      'ready_to_compare': 'جاهز للمقارنة',
      'select_two_notice': 'اختر رحلتين على الأقل للمقارنة.',
      'search_summary': 'ملخص البحث',
      'rides_label': 'الرحلات',
      'catalog_label': 'الكتالوج',
      'recent_searches': 'عمليات البحث الأخيرة',
      'clear': 'مسح',
      'no_recent_searches': 'لا توجد عمليات بحث حديثة',
      'demand_peak': 'طلب مرتفع',
      'demand_balanced': 'طلب مستقر',
      'demand_calm': 'طلب هادئ',
      'planning_tip_label': 'نصيحة التخطيط',
      'insights_center': 'مركز الرؤى',
      'view_full_insights': 'عرض لوحة الرؤى',
      'strategy_lab': 'مختبر الاستراتيجية',
      'strategy_lab_subtitle': 'صمّم مخطط الوردية التالية بحركات تنبؤية.',
      'open_strategy_lab': 'افتح مختبر الاستراتيجية',
      'wellness_studio': 'استوديو العافية',
      'wellness_intro': 'وازن وردياتك بلمسات يقظة سريعة.',
      'wellness_alignment': 'التناغم',
      'wellness_energy': 'الطاقة',
      'wellness_focus': 'التركيز',
      'wellness_check_in_title': 'فحص الوردية',
      'wellness_check_in_body': 'اضبط الطاقة والتركيز للحصول على إرشادات مخصصة.',
      'reset_rhythm': 'إعادة ضبط الإيقاع',
      'vibe_calm': 'صفاء هادئ',
      'vibe_focus': 'تركيز عميق',
      'vibe_energize': 'دفعة نشطة',
      'wellness_spotlight': 'طقس مميز',
      'wellness_completed': 'تم إنجازه اليوم',
      'wellness_tap_to_mark': 'اضغط للتحديد',
      'breath_sequences': 'تتابعات التنفس',
      'wellness_no_sequences': 'لا توجد تتابعات تنفس حالياً',
      'seconds_short': 'ث',
      'cycles_label': 'دورات',
      'mindful_rituals': 'طقوس يقظة',
      'wellness_no_rituals': 'لا توجد طقوس متاحة',
      'micro_breaks': 'استراحات قصيرة',
      'wellness_no_breaks': 'لا توجد استراحات مجدولة',
      'wellness_ai_tip_1': 'انسق الإيقاع المفضل مع نوافذ التخطيط لموازنة أسرع.',
      'wellness_ai_tip_2': 'الطقوس المكتملة ترفع مؤشر التناغم وثقة الهدف.',
      'wellness_ai_tip_3': 'سيخزن الاستوديو حالاتك اليومية لإطلاق توصيات أذكى لاحقاً.',
      'wellness_mini_header': 'نبض العافية السريع',
      'momentum_hub': 'استوديو الزخم',
      'momentum_pulse_title': 'نبض الزخم',
      'momentum_level': 'المستوى',
      'momentum_xp': 'نقاط الخبرة',
      'momentum_streak': 'سلسلة',
      'momentum_tracks_header': 'مسارات التركيز',
      'momentum_milestone_header': 'معالم المسار',
      'momentum_milestone_completed': 'تم إكمال المعلم! تم تعزيز الزخم.',
      'momentum_step_logged': 'تم تسجيل التقدم في المسار.',
      'momentum_done': 'منجز',
      'momentum_action_next': 'الخطوة التالية',
      'momentum_challenges_header': 'تحديات مباشرة',
      'momentum_challenge_complete': 'تم إكمال التحدي! تمت إضافة نقاط الخبرة.',
      'momentum_challenge_progress': 'تم تسجيل تقدم التحدي.',
      'momentum_mark_progress': 'تسجيل التقدم',
      'momentum_no_challenges': 'لا توجد تحديات نشطة حالياً.',
      'momentum_signals_header': 'إشارات المدرب',
      'momentum_refresh_toast': 'تم تحديث موجات الزخم.',
      'momentum_track_switched': 'تم تحديث مسار التركيز.',
      'momentum_ai_tip_1': 'ركز على مسار واحد في كل وردية للحفاظ على الزخم حاداً.',
      'momentum_ai_tip_2': 'تسجيل التقدم الصغير يزيد نقاط الخبرة ويكشف مستويات جديدة.',
      'momentum_ai_tip_3': 'إشارات المدرب تتجدد مع كل تحديث—انسقها مع مخطط الوردية.',
      'momentum_quick_header': 'لمحة الزخم',
      'community_lounge': 'صالون المجتمع',
      'community_refresh': 'تحديث النبض',
      'community_crews': 'دوائر السائقين',
      'community_beacons': 'المنارات المباشرة',
      'community_no_beacons': 'لا توجد منارات بعد — شارك أول إلهام.',
      'community_sprints': 'سباقات الطاقم',
      'community_no_sprints': 'لا توجد سباقات مجدولة حالياً.',
      'community_resources': 'الموارد المشتركة',
      'community_no_resources': 'لا توجد موارد محفوظة بعد.',
      'community_pulse': 'نبض المجتمع',
      'community_ai_tip': 'شارك منارة بعد كل وردية لتفعيل تعزيزات التعاون.',
      'community_collaboration': 'درجة التعاون',
      'community_share_rate': 'معدل المشاركة',
      'community_assist_rate': 'إيقاع المساندة',
      'community_active_drivers': 'سائقون نشطون',
      'community_energy': 'طاقة الدائرة',
      'community_next_sync': 'المزامنة القادمة',
      'community_boosts': 'تعزيزات',
      'community_boost': 'تعزيز',
      'community_boosted': 'تم التعزيز',
      'community_join_sprint': 'انضم للسباق',
      'community_sprint_joined': 'منضم',
      'community_save': 'حفظ',
      'community_saved': 'محفوظ',
      'community_quick_header': 'لمحة المجتمع',
      'community_open_full': 'افتح صالون المجتمع',
      'impact_studio': 'استوديو الأثر',
      'impact_refresh': 'تحديث نبض الأثر',
      'impact_focus_modes': 'أوضاع التركيز',
      'impact_theme_efficiency': 'الكفاءة',
      'impact_theme_sustainability': 'الاستدامة',
      'impact_theme_experience': 'متعة الراكب',
      'impact_pulse_title': 'نبض الأثر',
      'impact_city_label': 'النطاق الرئيسي',
      'impact_co2_saved': 'انبعاثات CO₂ الموفّرة',
      'impact_clean_km': 'كيلومترات نظيفة',
      'impact_renewable_share': 'نسبة الطاقة المتجددة',
      'impact_streak': 'سلسلة الأثر',
      'impact_streak_days': 'أيام',
      'impact_highlights': 'أبرز النتائج',
      'impact_goals': 'أهداف الأثر',
      'impact_goal_target': 'الهدف',
      'impact_goal_progress_hint': 'حرّك المنزلق لتسجيل تقدم اليوم.',
      'impact_initiatives': 'مبادرات الأثر',
      'impact_join': 'انضمام',
      'impact_joined': 'منضم',
      'impact_actions': 'خطوات دقيقة',
      'impact_mark_complete': 'وضع علامة منجز',
      'impact_completed': 'منجز',
      'impact_ripples': 'أصداء المدينة',
      'impact_quick_header': 'لمحة الأثر',
      'impact_open_full': 'افتح استوديو الأثر',
      'innovation_lab': 'مختبر الابتكار',
      'innovation_pulse_card': 'نبض الابتكار',
      'innovation_readiness': 'الجاهزية',
      'innovation_temperature': 'حرارة المختبر',
      'innovation_focus_lanes': 'مسارات التركيز',
      'innovation_energy_bursts': 'ومضات الطاقة',
      'innovation_rotate_focus': 'تدوير مسارات التركيز',
      'innovation_pipeline': 'خط النماذج الأولية',
      'innovation_no_prototypes': 'لا توجد نماذج أولية جاهزة بعد.',
      'innovation_stage': 'المرحلة',
      'innovation_confidence': 'الثقة',
      'innovation_next_step': 'الخطوة التالية',
      'innovation_last_note': 'ملاحظة المختبر',
      'innovation_advance': 'تطوير النموذج',
      'innovation_progress_updated': 'تم تحديث تقدم النموذج داخل المختبر.',
      'innovation_experiment_grid': 'التجارب النشطة',
      'innovation_no_experiments': 'لا توجد تجارب قيد التشغيل بعد.',
      'innovation_blueprint_deck': 'مجموعة المخططات',
      'innovation_no_blueprints': 'لا توجد مخططات جاهزة بعد.',
      'innovation_owner': 'المالك',
      'innovation_horizon': 'الأفق',
      'innovation_ai_headline': 'لمحة ذكاء المختبر',
      'innovation_ready_score_label': 'مستوى الجاهزية',
      'innovation_focus_lane_label': 'مسارات التركيز',
      'innovation_next_review_on': 'المراجعة القادمة: {slot}',
      'mastery_studio': 'استوديو الإتقان',
      'mastery_quick_header': 'نبض الإتقان',
      'mastery_progress': 'الزخم',
      'mastery_energy_level': 'الطاقة',
      'mastery_micro_practice': 'ممارسة صغيرة',
      'mastery_module_progress_label': 'تقدم الوحدة',
      'mastery_focus_pathways': 'مسارات التركيز',
      'mastery_mark_lesson': 'تمرين منجز',
      'mastery_lessons_done': 'الدروس المكتملة',
      'mastery_next_action': 'الخطوة التالية',
      'mastery_focus_active': 'التركيز مفعل',
      'mastery_focus_toggle': 'تعيين كتركيز',
      'mastery_workshops_title': 'ورش قادمة',
      'mastery_enroll': 'انضمام',
      'mastery_leave': 'مغادرة',
      'mastery_badges_title': 'شارات قيد التقدم',
      'mastery_badge_unlocked': 'تم الفتح',
      'mastery_badge_locked': 'مقفل',
      'mastery_reflections_title': 'تأملات',
      'mastery_reflection_placeholder': 'ماذا تعلمت اليوم؟',
      'mastery_save_reflection': 'حفظ التأمل',
      'mastery_empty_reflections': 'لا توجد تأملات بعد.',
      'mastery_refresh': 'تحديث النبض',
      'mastery_ai_hint': 'رؤية تكتيكية',
      'mastery_coach_message': 'ملاحظة المدرب',
      'mastery_focus_label': 'التركيز',
      'mastery_view_full': 'افتح استوديو الإتقان',
      'horizon_studio': 'استوديو الأفق',
      'horizon_ai_headline': 'رؤى الأفق المستقبلية',
      'horizon_ai_alignment': 'درجة المواءمة',
      'horizon_ai_confidence': 'مستوى الثقة',
      'horizon_ai_focus': 'محاور التركيز',
      'horizon_ai_signals': 'إشارات مميزة',
      'horizon_ai_window': 'نافذة النبض التالية: {slot}',
      'horizon_ai_question': 'سؤال موجه: {question}',
      'horizon_pulse_card': 'نبض المستقبل',
      'horizon_alignment': 'المواءمة',
      'horizon_confidence': 'الثقة',
      'horizon_runway_days': 'أيام الاستعداد',
      'horizon_next_window': 'النافذة التالية',
      'horizon_guiding_question': 'سؤال موجه',
      'horizon_focus_themes': 'محاور التركيز',
      'horizon_signal_highlights': 'إشارات بارزة',
      'horizon_raise_alignment': 'رفع المواءمة',
      'horizon_cool_alignment': 'تهدئة المواءمة',
      'horizon_refresh_pulse': 'تحديث النبض',
      'horizon_scenarios': 'السيناريوهات قيد المراقبة',
      'horizon_probability': 'الاحتمال',
      'horizon_impact': 'التأثير',
      'horizon_focus_cta': 'تعيين كتركيز',
      'horizon_focus_active': 'تركيز نشط',
      'horizon_runway': 'قائمة استعداد',
      'horizon_flag_signal': 'تثبيت الإشارة',
      'horizon_unflag_signal': 'إلغاء تثبيت الإشارة',
      'horizon_signals': 'لوحة الإشارات',
      'horizon_momentum': 'الزخم',
      'horizon_blueprints': 'لوحة المخططات',
      'horizon_advance_blueprint': 'تقدم المرحلة',
      'horizon_actions_label': 'إجراءات مصغرة',
      'horizon_quick_header': 'لمحة الأفق',
      'horizon_open_full': 'افتح استوديو الأفق',
      'fusion_studio': 'استوديو الاندماج',
      'fusion_intro':
          'ادمج مسارات التركيز والتجارب لفتح رحلات ركاب أكثر ثراء.',
      'fusion_ai_headline': 'لمحة ذكاء اندماجية',
      'fusion_alignment': 'التوافق',
      'fusion_cohesion': 'التماسك',
      'fusion_window_label': 'النافذة',
      'fusion_focus_label': 'مسار التركيز',
      'fusion_next_sync': 'المزامنة التالية',
      'fusion_refresh': 'تحديث نبض الاندماج',
      'fusion_strands_title': 'خيوط التركيز',
      'fusion_flow': 'التدفق',
      'fusion_canvas_title': 'مسارات اللوحة',
      'fusion_canvas_empty': 'لا توجد مسارات لوحة متاحة بعد.',
      'fusion_canvas_heat': 'الحرارة',
      'fusion_canvas_cohesion': 'التماسك',
      'fusion_experiments_title': 'التجارب',
      'fusion_experiments_empty': 'لم يتم إطلاق تجارب بعد.',
      'fusion_confidence': 'الثقة',
      'fusion_stage': 'المرحلة',
      'fusion_activate': 'تفعيل',
      'fusion_pause': 'إيقاف',
      'fusion_signals_title': 'الإشارات',
      'fusion_signals_empty': 'لا توجد إشارات مكتشفة بعد.',
      'fusion_capture': 'التقاط',
      'fusion_release': 'إطلاق',
      'fusion_quick_header': 'لمحة الاندماج',
      'fusion_quick_focus': 'التركيز',
      'fusion_quick_alignment': 'التوافق',
      'fusion_quick_cohesion': 'التماسك',
      'fusion_quick_open': 'افتح استوديو الاندماج',
      'cosmos_studio': 'استوديو الكون',
      'cosmos_pulse_title': 'نبض الكوكبات',
      'cosmos_magnetism': 'المغناطيسية',
      'cosmos_signal': 'قوة الإشارة',
      'cosmos_alliances': 'التحالفات النشطة',
      'cosmos_window_label': 'النافذة',
      'cosmos_focus_label': 'التركيز',
      'cosmos_next_trajectory': 'المسار التالي',
      'cosmos_constellations_title': 'مجال الكوكبات',
      'cosmos_resonance': 'الرنين',
      'cosmos_tap_to_focus': 'اضغط لتغيير التركيز',
      'cosmos_orbits_title': 'مسارات المدار',
      'cosmos_beacons_title': 'منارات التعزيز',
      'cosmos_urgency': 'الإلحاح',
      'cosmos_boost': 'تعزيز',
      'cosmos_release': 'تحرير',
      'cosmos_expeditions_title': 'الحملات',
      'cosmos_enroll': 'انضم إلى الحملة',
      'cosmos_leave': 'غادر الحملة',
      'cosmos_artifacts_title': 'خزانة القطع',
      'cosmos_save': 'حفظ',
      'cosmos_saved': 'محفوظ',
      'cosmos_intro': 'تابع مسارات التحالف وتعزيزات المدار خلال نوبتك.',
      'cosmos_refresh': 'تحديث نبض الكون',
      'cosmos_boosted_message': 'تم تفعيل تعزيز المنارة.',
      'cosmos_unboosted_message': 'تم إلغاء تعزيز المنارة.',
      'cosmos_enrolled_message': 'تم جدولة الحملة لليلة.',
      'cosmos_removed_message': 'تم إيقاف الحملة مؤقتاً.',
      'cosmos_saved_message': 'تم حفظ القطعة في الخزانة.',
      'cosmos_unsaved_message': 'تم إزالة القطعة من الخزانة.',
      'cosmos_quick_header': 'لمحة الكون',
      'cosmos_quick_window': 'النافذة النشطة',
      'cosmos_quick_focus': 'قوس التركيز',
      'cosmos_quick_open': 'افتح استوديو الكون',
      'impact_focus_updated': 'تم تحديث وضع التركيز.',
      'impact_goal_updated': 'تم تحديث هدف الأثر.',
      'impact_initiative_joined_toast': 'تم حفظ تفضيل المبادرة.',
      'impact_action_completed_toast': 'تم تسجيل الخطوة.',
      'impact_ai_tip':
          'سيضيف الذكاء الاصطناعي لاحقاً توصيات بيئية أوسع تلقائياً.',
      'open_wellness_full': 'فتح استوديو العافية',
      'weekly_goal': 'الهدف الأسبوعي للأرباح',
      'goal_progress': 'مدى التقدم نحو الهدف',
      'goal_recommendation': 'الهدف المقترح:',
      'goal_reached': 'لقد وصلت إلى هدفك بالفعل!',
      'target_reach_estimate': 'متوقع الوصول خلال',
      'adjust_goal': 'تعديل الهدف',
      'minutes_short': 'دقيقة',
      'rides_short': 'رحلات',
      'heatmap_hint': 'تشير شدة اللون إلى فرص الطلب في كل فترة.',
      'focus_areas': 'مناطق التركيز',
      'demand_heatmap': 'خريطة الطلب الحرارية',
      'trend_pulses': 'نبضات فورية',
      'refresh_insights': 'تحديث الرؤى',
      'trend_rising': 'متصاعد',
      'trend_cooling': 'متراجع',
      'trend_flat': 'مستقر',
      'goal_updated': 'تم تحديث الهدف',
      'weekday_mon': 'الاثنين',
      'weekday_tue': 'الثلاثاء',
      'weekday_wed': 'الأربعاء',
      'weekday_thu': 'الخميس',
      'weekday_fri': 'الجمعة',
      'weekday_sat': 'السبت',
      'weekday_sun': 'الأحد',
      'slot_morning': 'الصباح',
      'slot_midday': 'منتصف النهار',
      'slot_evening': 'المساء',
      'planner_projected_earnings': 'الأرباح المتوقعة',
      'planner_expected_trips': 'الرحلات المتوقعة',
      'planner_avg_demand': 'متوسط الطلب',
      'planner_confidence': 'مستوى الثقة',
      'planner_focus_label': 'دقائق التركيز',
      'planner_autonomous_mode': 'تعزيز تلقائي',
      'planner_autonomous_hint': 'فعّل التنبيهات الاستباقية وتسلسل الذكاء.',
      'planner_metrics_label': 'مؤشرات السيناريو',
      'planner_timeline': 'مخطط الزمن',
      'planner_actions': 'خطوات الزخم',
      'planner_regenerate': 'إعادة توليد الخطة',
      'planner_focus_area': 'منطقة التركيز',
      'planner_surge': 'رفع التسعير',
      'planner_risk': 'المخاطرة',
      'planner_tags': 'الوسوم',
      'planner_impact': 'الأثر',
    },
  };

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['en']![key] ??
        key;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  static const supportedLocales = [Locale('en'), Locale('ar')];
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate old) => false;
}
