import 'dart:async';

import 'package:flutter/material.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const _localizedValues = <String, Map<String, String>>{
    'en': {
      'app_name': 'Driver Pro',
      'next': 'Next',
      'skip': 'Skip',
      'get_started': 'Get Started',
      'login': 'Login',
      'register': 'Register',
      'continue_guest': 'Continue as Guest',
      'email_or_phone': 'Email or phone',
      'password': 'Password',
      'home': 'Home',
      'enable_location': 'Enable Location',
      'enable_location_description':
          'Turn on your location services to start accepting rides.',
      'continue': 'Continue',
      'incoming_ride': 'Incoming Ride',
      'accept': 'Accept',
      'decline': 'Decline',
      'online': 'Online',
      'offline': 'Offline',
      'earnings': 'Earnings',
      'history': 'History',
      'my_rides': 'My Rides',
      'performance': 'Performance',
      'settings': 'Settings',
      'language': 'Language',
      'dark_mode': 'Dark Mode',
      'primary_color': 'Primary color',
      'notifications': 'Notifications',
      'ai_placeholder': 'AI insights coming soon.',
      'search': 'Search',
      'guest': 'Guest',
      'logout': 'Logout',
      'profile': 'Profile',
      'documents': 'Documents',
      'help': 'Help & FAQ',
      'catalog': 'Catalog',
      'compare': 'Compare',
      'onboarding_title_1': 'Drive smarter',
      'onboarding_desc_1': 'Discover smarter ways to navigate your city.',
      'onboarding_title_2': 'Earn confidently',
      'onboarding_desc_2': 'Track earnings and stay on top of your goals.',
      'onboarding_title_3': 'Stay connected',
      'onboarding_desc_3': 'Chat with passengers and support instantly.',
      'my_earnings_title': 'My Earnings',
      'add_new_card': 'Add new card',
      'available_balance': 'Available balance',
      'no_rides_found': 'No rides found',
      'search_history': 'Search history',
      'search_catalog': 'Search catalog',
      'catalog_items': 'Catalog Items',
      'compare_items': 'Compare Items',
      'documents_title': 'Documents',
      'upload': 'Upload',
      'contact_support': 'Contact Support',
      'chats': 'Chats',
      'on_trip_title': 'On Trip',
      'rate_trip': 'Rate Trip',
      'how_was_trip': 'How was your trip?',
      'submit': 'Submit',
      'cancel': 'Cancel',
      'no_completed_trip': 'No completed trip.',
      'no_active_trip': 'No active trip.',
      'no_catalog_found': 'No catalog items found',
      'save': 'Save',
      'profile_title': 'Profile',
      'settings_title': 'Settings',
      'search_data': 'Search data',
      'rides_section': 'Rides',
      'calling': 'Calling...',
      'message_sent': 'Message sent',
      'status': 'Status',
      'metric': 'Metric',
      'total_trips': 'Total trips',
      'completion_rate': 'Completion rate',
      'average_rating': 'Average rating',
      'total_distance': 'Total distance',
      'no_rides_available': 'No rides available',
      'pickup': 'Pickup',
      'destination': 'Destination',
      'invalid_credentials': 'Invalid credentials',
      'forgot_password': 'Forgot password?',
      'send_reset_link': 'Send reset link',
      'required': 'Required',
      'enter_valid_email_phone': 'Enter valid email or phone',
      'password_too_short': 'Password too short',
      'name': 'Name',
      'email': 'Email',
      'phone': 'Phone',
      'confirm_password': 'Confirm Password',
      'update_avatar': 'Update avatar URL',
      'close': 'Close',
      'profile_updated': 'Profile updated locally.',
      'car_model': 'Car model',
      'car_plate': 'Car plate',
      'passwords_do_not_match': 'Passwords do not match',
      'trip_details': 'Trip Details',
      'call': 'Call',
      'message': 'Message',
      'select_items_to_compare': 'Select items to compare.',
      'price': 'Price',
      'distance': 'Distance',
      'time': 'Time',
      'smart_insights': 'Smart insights',
      'ride_insights': 'Ride insights',
      'catalog_insights': 'Catalog insights',
      'projected_payout_label': 'Projected payout',
      'surge_multiplier_label': 'Surge multiplier',
      'cancellation_risk_label': 'Cancellation risk',
      'demand_trend_label': 'Demand trend',
      'distance_hint_label': 'Distance insight',
      'bundle_value_label': 'Bundle value',
      'rating_strength_label': 'Rating strength',
      'shift_planner': 'Shift planner',
      'suggested_follow_up': 'Suggested follow-up',
      'hotspot_window': 'Hotspot window',
      'selected_label': 'Selected',
      'ready_to_compare': 'Ready to compare',
      'select_two_notice': 'Pick at least two rides to compare.',
      'search_summary': 'Search summary',
      'rides_label': 'Rides',
      'catalog_label': 'Catalog',
      'recent_searches': 'Recent searches',
      'clear': 'Clear',
      'no_recent_searches': 'No recent searches yet',
      'demand_peak': 'Peak demand',
      'demand_balanced': 'Steady demand',
      'demand_calm': 'Calm demand',
      'planning_tip_label': 'Planning tip',
      'insights_center': 'Insights studio',
      'view_full_insights': 'View full insights',
      'strategy_lab': 'Strategy lab',
      'strategy_lab_subtitle': 'Design the next shift blueprint with predictive plays.',
      'open_strategy_lab': 'Open strategy lab',
      'wellness_studio': 'Wellness studio',
      'wellness_intro': 'Balance your shift with mindful resets and momentum.',
      'wellness_alignment': 'Alignment',
      'wellness_energy': 'Energy',
      'wellness_focus': 'Focus',
      'wellness_check_in_title': 'Shift check-in',
      'wellness_check_in_body': 'Tune energy and focus to personalise your boosts.',
      'reset_rhythm': 'Reset rhythm',
      'vibe_calm': 'Calm clarity',
      'vibe_focus': 'Deep focus',
      'vibe_energize': 'Active boost',
      'wellness_spotlight': 'Spotlight ritual',
      'wellness_completed': 'Completed today',
      'wellness_tap_to_mark': 'Tap to log progress',
      'breath_sequences': 'Breath sequences',
      'wellness_no_sequences': 'No breath sequences yet',
      'seconds_short': 's',
      'cycles_label': 'cycles',
      'mindful_rituals': 'Mindful rituals',
      'wellness_no_rituals': 'No rituals available yet',
      'micro_breaks': 'Micro breaks',
      'wellness_no_breaks': 'No micro breaks queued',
      'wellness_ai_tip_1': 'Pair your preferred vibe with planner windows for smarter resets.',
      'wellness_ai_tip_2': 'Completed rituals nudge alignment and goal confidence.',
      'wellness_ai_tip_3': 'Daily check-ins will power richer guidance in upcoming releases.',
      'wellness_mini_header': 'Mind-body snapshot',
      'momentum_hub': 'Momentum studio',
      'momentum_pulse_title': 'Momentum pulse',
      'momentum_level': 'Level',
      'momentum_xp': 'XP',
      'momentum_streak': 'Streak',
      'momentum_tracks_header': 'Focus tracks',
      'momentum_milestone_header': 'Track milestones',
      'momentum_milestone_completed': 'Milestone complete! Momentum boosted.',
      'momentum_step_logged': 'Progress logged into your track.',
      'momentum_done': 'Completed',
      'momentum_action_next': 'Next action',
      'momentum_challenges_header': 'Live challenges',
      'momentum_challenge_complete': 'Challenge complete! XP rewarded.',
      'momentum_challenge_progress': 'Challenge progress logged.',
      'momentum_mark_progress': 'Log progress',
      'momentum_no_challenges': 'No active challenges right now.',
      'momentum_signals_header': 'Coach signals',
      'momentum_refresh_toast': 'Momentum streams refreshed.',
      'momentum_track_switched': 'Focus track updated.',
      'momentum_ai_tip_1':
          'Dial into one focus track per shift to keep momentum sharp.',
      'momentum_ai_tip_2':
          'Logging micro-progress nudges XP gains and unlocks new levels.',
      'momentum_ai_tip_3':
          'Coach signals remix with each refresh—sync them with planner cues.',
      'momentum_quick_header': 'Momentum snapshot',
      'open_wellness_full': 'Open wellness studio',
      'weekly_goal': 'Weekly earning goal',
      'goal_progress': 'Goal progress',
      'goal_recommendation': 'Recommended target:',
      'goal_reached': 'Great! You already reached your goal.',
      'target_reach_estimate': 'Projected to reach in',
      'adjust_goal': 'Adjust goal',
      'minutes_short': 'min',
      'rides_short': 'rides',
      'heatmap_hint': 'Intensity indicates demand opportunity by block.',
      'focus_areas': 'Focus areas',
      'demand_heatmap': 'Demand heatmap',
      'trend_pulses': 'Live pulses',
      'refresh_insights': 'Refresh insights',
      'trend_rising': 'Rising',
      'trend_cooling': 'Cooling',
      'trend_flat': 'Steady',
      'goal_updated': 'Goal updated',
      'weekday_mon': 'Mon',
      'weekday_tue': 'Tue',
      'weekday_wed': 'Wed',
      'weekday_thu': 'Thu',
      'weekday_fri': 'Fri',
      'weekday_sat': 'Sat',
      'weekday_sun': 'Sun',
      'slot_morning': 'Morning',
      'slot_midday': 'Midday',
      'slot_evening': 'Evening',
      'planner_projected_earnings': 'Projected earnings',
      'planner_expected_trips': 'Expected trips',
      'planner_avg_demand': 'Average demand',
      'planner_confidence': 'Confidence',
      'planner_focus_label': 'Focus minutes',
      'planner_autonomous_mode': 'Autopilot boost',
      'planner_autonomous_hint': 'Enable proactive nudges and smart stacking.',
      'planner_metrics_label': 'Scenario metrics',
      'planner_timeline': 'Timeline blueprint',
      'planner_actions': 'Momentum actions',
      'planner_regenerate': 'Re-simulate plan',
      'planner_focus_area': 'Focus area',
      'planner_surge': 'Surge lift',
      'planner_risk': 'Risk',
      'planner_tags': 'Tags',
      'planner_impact': 'Impact',
    },
    'ar': {
      'app_name': 'سائق برو',
      'next': 'التالي',
      'skip': 'تخطي',
      'get_started': 'ابدأ الآن',
      'login': 'تسجيل الدخول',
      'register': 'إنشاء حساب',
      'continue_guest': 'المتابعة كضيف',
      'email_or_phone': 'البريد أو الهاتف',
      'password': 'كلمة المرور',
      'home': 'الرئيسية',
      'enable_location': 'تفعيل الموقع',
      'enable_location_description':
          'قم بتشغيل خدمات الموقع لبدء قبول الرحلات.',
      'continue': 'متابعة',
      'incoming_ride': 'رحلة واردة',
      'accept': 'قبول',
      'decline': 'رفض',
      'online': 'متصل',
      'offline': 'غير متصل',
      'earnings': 'الأرباح',
      'history': 'السجل',
      'my_rides': 'رحلاتي',
      'performance': 'الأداء',
      'settings': 'الإعدادات',
      'language': 'اللغة',
      'dark_mode': 'الوضع الداكن',
      'primary_color': 'اللون الرئيسي',
      'notifications': 'الإشعارات',
      'ai_placeholder': 'تحليلات الذكاء الاصطناعي قريباً.',
      'search': 'بحث',
      'guest': 'ضيف',
      'logout': 'تسجيل الخروج',
      'profile': 'الملف الشخصي',
      'documents': 'الوثائق',
      'help': 'المساعدة والأسئلة',
      'catalog': 'كتالوج',
      'compare': 'مقارنة',
      'onboarding_title_1': 'قد بأذكى طريقة',
      'onboarding_desc_1': 'اكتشف طرقاً أذكى للتنقل في مدينتك.',
      'onboarding_title_2': 'اربح بثقة',
      'onboarding_desc_2': 'تابع أرباحك وحقق أهدافك.',
      'onboarding_title_3': 'ابقَ على اتصال',
      'onboarding_desc_3': 'تواصل مع الركاب والدعم فوراً.',
      'my_earnings_title': 'أرباحي',
      'add_new_card': 'إضافة بطاقة جديدة',
      'available_balance': 'الرصيد المتاح',
      'no_rides_found': 'لا توجد رحلات',
      'search_history': 'بحث في السجل',
      'search_catalog': 'بحث في الكتالوج',
      'catalog_items': 'عناصر الكتالوج',
      'compare_items': 'مقارنة العناصر',
      'documents_title': 'الوثائق',
      'upload': 'رفع',
      'contact_support': 'اتصل بالدعم',
      'chats': 'المحادثات',
      'on_trip_title': 'رحلة جارية',
      'rate_trip': 'تقييم الرحلة',
      'how_was_trip': 'كيف كانت رحلتك؟',
      'submit': 'إرسال',
      'cancel': 'إلغاء',
      'no_completed_trip': 'لا توجد رحلة مكتملة.',
      'no_active_trip': 'لا توجد رحلة نشطة.',
      'no_catalog_found': 'لا توجد عناصر كتالوج',
      'save': 'حفظ',
      'profile_title': 'الملف الشخصي',
      'settings_title': 'الإعدادات',
      'search_data': 'بحث في البيانات',
      'rides_section': 'الرحلات',
      'calling': 'جارٍ الاتصال...',
      'message_sent': 'تم إرسال الرسالة',
      'status': 'الحالة',
      'metric': 'المؤشر',
      'total_trips': 'إجمالي الرحلات',
      'completion_rate': 'نسبة الإكمال',
      'average_rating': 'متوسط التقييم',
      'total_distance': 'إجمالي المسافة',
      'no_rides_available': 'لا توجد رحلات متاحة',
      'pickup': 'الانطلاق',
      'destination': 'الوجهة',
      'invalid_credentials': 'بيانات دخول غير صحيحة',
      'forgot_password': 'نسيت كلمة المرور؟',
      'send_reset_link': 'إرسال رابط إعادة التعيين',
      'required': 'مطلوب',
      'enter_valid_email_phone': 'أدخل بريداً إلكترونياً أو هاتفاً صالحاً',
      'password_too_short': 'كلمة المرور قصيرة',
      'name': 'الاسم',
      'email': 'البريد الإلكتروني',
      'phone': 'الهاتف',
      'confirm_password': 'تأكيد كلمة المرور',
      'update_avatar': 'تحديث رابط الصورة',
      'close': 'إغلاق',
      'profile_updated': 'تم تحديث الملف محلياً.',
      'car_model': 'طراز السيارة',
      'car_plate': 'رقم اللوحة',
      'passwords_do_not_match': 'كلمتا المرور غير متطابقتين',
      'trip_details': 'تفاصيل الرحلة',
      'call': 'اتصال',
      'message': 'رسالة',
      'select_items_to_compare': 'اختر عناصر للمقارنة.',
      'price': 'السعر',
      'distance': 'المسافة',
      'time': 'الوقت',
      'smart_insights': 'رؤى ذكية',
      'ride_insights': 'تحليلات الرحلة',
      'catalog_insights': 'تحليلات الكتالوج',
      'projected_payout_label': 'العائد المتوقع',
      'surge_multiplier_label': 'معامل التسعير',
      'cancellation_risk_label': 'مخاطر الإلغاء',
      'demand_trend_label': 'اتجاه الطلب',
      'distance_hint_label': 'معلومة المسافة',
      'bundle_value_label': 'قيمة الباقة',
      'rating_strength_label': 'قوة التقييم',
      'shift_planner': 'مخطط الوردية',
      'suggested_follow_up': 'اقتراح الرحلة التالية',
      'hotspot_window': 'نافذة النقاط الساخنة',
      'selected_label': 'المحدد',
      'ready_to_compare': 'جاهز للمقارنة',
      'select_two_notice': 'اختر رحلتين على الأقل للمقارنة.',
      'search_summary': 'ملخص البحث',
      'rides_label': 'الرحلات',
      'catalog_label': 'الكتالوج',
      'recent_searches': 'عمليات البحث الأخيرة',
      'clear': 'مسح',
      'no_recent_searches': 'لا توجد عمليات بحث حديثة',
      'demand_peak': 'طلب مرتفع',
      'demand_balanced': 'طلب مستقر',
      'demand_calm': 'طلب هادئ',
      'planning_tip_label': 'نصيحة التخطيط',
      'insights_center': 'مركز الرؤى',
      'view_full_insights': 'عرض لوحة الرؤى',
      'strategy_lab': 'مختبر الاستراتيجية',
      'strategy_lab_subtitle': 'صمّم مخطط الوردية التالية بحركات تنبؤية.',
      'open_strategy_lab': 'افتح مختبر الاستراتيجية',
      'wellness_studio': 'استوديو العافية',
      'wellness_intro': 'وازن وردياتك بلمسات يقظة سريعة.',
      'wellness_alignment': 'التناغم',
      'wellness_energy': 'الطاقة',
      'wellness_focus': 'التركيز',
      'wellness_check_in_title': 'فحص الوردية',
      'wellness_check_in_body': 'اضبط الطاقة والتركيز للحصول على إرشادات مخصصة.',
      'reset_rhythm': 'إعادة ضبط الإيقاع',
      'vibe_calm': 'صفاء هادئ',
      'vibe_focus': 'تركيز عميق',
      'vibe_energize': 'دفعة نشطة',
      'wellness_spotlight': 'طقس مميز',
      'wellness_completed': 'تم إنجازه اليوم',
      'wellness_tap_to_mark': 'اضغط للتحديد',
      'breath_sequences': 'تتابعات التنفس',
      'wellness_no_sequences': 'لا توجد تتابعات تنفس حالياً',
      'seconds_short': 'ث',
      'cycles_label': 'دورات',
      'mindful_rituals': 'طقوس يقظة',
      'wellness_no_rituals': 'لا توجد طقوس متاحة',
      'micro_breaks': 'استراحات قصيرة',
      'wellness_no_breaks': 'لا توجد استراحات مجدولة',
      'wellness_ai_tip_1': 'انسق الإيقاع المفضل مع نوافذ التخطيط لموازنة أسرع.',
      'wellness_ai_tip_2': 'الطقوس المكتملة ترفع مؤشر التناغم وثقة الهدف.',
      'wellness_ai_tip_3': 'سيخزن الاستوديو حالاتك اليومية لإطلاق توصيات أذكى لاحقاً.',
      'wellness_mini_header': 'نبض العافية السريع',
      'momentum_hub': 'استوديو الزخم',
      'momentum_pulse_title': 'نبض الزخم',
      'momentum_level': 'المستوى',
      'momentum_xp': 'نقاط الخبرة',
      'momentum_streak': 'سلسلة',
      'momentum_tracks_header': 'مسارات التركيز',
      'momentum_milestone_header': 'معالم المسار',
      'momentum_milestone_completed': 'تم إكمال المعلم! تم تعزيز الزخم.',
      'momentum_step_logged': 'تم تسجيل التقدم في المسار.',
      'momentum_done': 'منجز',
      'momentum_action_next': 'الخطوة التالية',
      'momentum_challenges_header': 'تحديات مباشرة',
      'momentum_challenge_complete': 'تم إكمال التحدي! تمت إضافة نقاط الخبرة.',
      'momentum_challenge_progress': 'تم تسجيل تقدم التحدي.',
      'momentum_mark_progress': 'تسجيل التقدم',
      'momentum_no_challenges': 'لا توجد تحديات نشطة حالياً.',
      'momentum_signals_header': 'إشارات المدرب',
      'momentum_refresh_toast': 'تم تحديث موجات الزخم.',
      'momentum_track_switched': 'تم تحديث مسار التركيز.',
      'momentum_ai_tip_1': 'ركز على مسار واحد في كل وردية للحفاظ على الزخم حاداً.',
      'momentum_ai_tip_2': 'تسجيل التقدم الصغير يزيد نقاط الخبرة ويكشف مستويات جديدة.',
      'momentum_ai_tip_3': 'إشارات المدرب تتجدد مع كل تحديث—انسقها مع مخطط الوردية.',
      'momentum_quick_header': 'لمحة الزخم',
      'open_wellness_full': 'فتح استوديو العافية',
      'weekly_goal': 'الهدف الأسبوعي للأرباح',
      'goal_progress': 'مدى التقدم نحو الهدف',
      'goal_recommendation': 'الهدف المقترح:',
      'goal_reached': 'لقد وصلت إلى هدفك بالفعل!',
      'target_reach_estimate': 'متوقع الوصول خلال',
      'adjust_goal': 'تعديل الهدف',
      'minutes_short': 'دقيقة',
      'rides_short': 'رحلات',
      'heatmap_hint': 'تشير شدة اللون إلى فرص الطلب في كل فترة.',
      'focus_areas': 'مناطق التركيز',
      'demand_heatmap': 'خريطة الطلب الحرارية',
      'trend_pulses': 'نبضات فورية',
      'refresh_insights': 'تحديث الرؤى',
      'trend_rising': 'متصاعد',
      'trend_cooling': 'متراجع',
      'trend_flat': 'مستقر',
      'goal_updated': 'تم تحديث الهدف',
      'weekday_mon': 'الاثنين',
      'weekday_tue': 'الثلاثاء',
      'weekday_wed': 'الأربعاء',
      'weekday_thu': 'الخميس',
      'weekday_fri': 'الجمعة',
      'weekday_sat': 'السبت',
      'weekday_sun': 'الأحد',
      'slot_morning': 'الصباح',
      'slot_midday': 'منتصف النهار',
      'slot_evening': 'المساء',
      'planner_projected_earnings': 'الأرباح المتوقعة',
      'planner_expected_trips': 'الرحلات المتوقعة',
      'planner_avg_demand': 'متوسط الطلب',
      'planner_confidence': 'مستوى الثقة',
      'planner_focus_label': 'دقائق التركيز',
      'planner_autonomous_mode': 'تعزيز تلقائي',
      'planner_autonomous_hint': 'فعّل التنبيهات الاستباقية وتسلسل الذكاء.',
      'planner_metrics_label': 'مؤشرات السيناريو',
      'planner_timeline': 'مخطط الزمن',
      'planner_actions': 'خطوات الزخم',
      'planner_regenerate': 'إعادة توليد الخطة',
      'planner_focus_area': 'منطقة التركيز',
      'planner_surge': 'رفع التسعير',
      'planner_risk': 'المخاطرة',
      'planner_tags': 'الوسوم',
      'planner_impact': 'الأثر',
    },
  };

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['en']![key] ??
        key;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  static const supportedLocales = [Locale('en'), Locale('ar')];
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate old) => false;
}
